export * from './getLauncherDir'
export * from './getRamForMc'
export * from './getVersion'
export * from './git'
export * from './isInstalled'
export * as minecraft from './minecraft'
export * from './removeOldVersion'
